name: build-nanogpt
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - jupyter
  - ipykernel
  - tqdm

  # --------------------
  # PyTorch + CUDA
  # --------------------
  - pytorch>=2.1
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8

  # --------------------
  # Utils
  # --------------------
  - psutil

  # --------------------
  # Hugging Face stack
  # --------------------
  - pip:
      - transformers>=4.40
      - datasets>=2.19.2
      - accelerate>=0.30
      - peft>=0.11
      - evaluate>=0.4
      - sentencepiece
